// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuZDeJsbHbrNBYw01C_O-JOptdeb63QzM',
    appId: '1:634554212692:web:0db1570b1f3ae68908e8c1',
    messagingSenderId: '634554212692',
    projectId: 'smart-baby-band',
    authDomain: 'smart-baby-band.firebaseapp.com',
    databaseURL: 'https://smart-baby-band-default-rtdb.firebaseio.com',
    storageBucket: 'smart-baby-band.firebasestorage.app',
    measurementId: 'G-TYYD3P8J7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmNHLfO5Me8BG7dwy-Am1gq4dMmbOfpHQ',
    appId: '1:634554212692:android:1d1616bb276353ab08e8c1',
    messagingSenderId: '634554212692',
    projectId: 'smart-baby-band',
    databaseURL: 'https://smart-baby-band-default-rtdb.firebaseio.com',
    storageBucket: 'smart-baby-band.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD9pa0M9LinDzOiuHiBTfSqU8seDrPrrA',
    appId: '1:634554212692:ios:2f1f4e9475f1ed5a08e8c1',
    messagingSenderId: '634554212692',
    projectId: 'smart-baby-band',
    databaseURL: 'https://smart-baby-band-default-rtdb.firebaseio.com',
    storageBucket: 'smart-baby-band.firebasestorage.app',
    iosBundleId: 'com.example.babytest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD9pa0M9LinDzOiuHiBTfSqU8seDrPrrA',
    appId: '1:634554212692:ios:2f1f4e9475f1ed5a08e8c1',
    messagingSenderId: '634554212692',
    projectId: 'smart-baby-band',
    databaseURL: 'https://smart-baby-band-default-rtdb.firebaseio.com',
    storageBucket: 'smart-baby-band.firebasestorage.app',
    iosBundleId: 'com.example.babytest1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuZDeJsbHbrNBYw01C_O-JOptdeb63QzM',
    appId: '1:634554212692:web:dbdfb487e9ffabe508e8c1',
    messagingSenderId: '634554212692',
    projectId: 'smart-baby-band',
    authDomain: 'smart-baby-band.firebaseapp.com',
    databaseURL: 'https://smart-baby-band-default-rtdb.firebaseio.com',
    storageBucket: 'smart-baby-band.firebasestorage.app',
    measurementId: 'G-LDCCBS69S9',
  );
}
