"""
Baby Profile Model — Defines the structure of a baby profile in Firestore.

Firestore Collection: 'baby_profiles'
Document ID: Auto-generated by Firestore

Each user (parent) can have one or more baby profiles.
Each baby is linked to an ESP32 device via device_id.
"""

from dataclasses import dataclass, field
from datetime import datetime, date
from typing import Optional


@dataclass
class BabyProfile:
    """
    Represents a baby's profile.

    Firestore path: baby_profiles/{auto_id}
    """
    user_id: str                      # Firebase Auth UID of the parent
    name: str                         # Baby's name (e.g., "Emma")
    date_of_birth: Optional[str] = None  # ISO format: "2025-09-15"
    gender: Optional[str] = None      # "male", "female", or "other"
    device_id: Optional[str] = None   # ESP32 device identifier
    avatar_url: Optional[str] = None  # Profile picture URL
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: Optional[datetime] = None

    def to_dict(self) -> dict:
        """Convert to dictionary for Firestore storage."""
        return {
            "user_id": self.user_id,
            "name": self.name,
            "date_of_birth": self.date_of_birth,
            "gender": self.gender,
            "device_id": self.device_id,
            "avatar_url": self.avatar_url,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }

    @staticmethod
    def from_dict(doc_id: str, data: dict) -> "BabyProfile":
        """Create BabyProfile instance from Firestore document."""
        profile = BabyProfile(
            user_id=data.get("user_id", ""),
            name=data.get("name", ""),
            date_of_birth=data.get("date_of_birth"),
            gender=data.get("gender"),
            device_id=data.get("device_id"),
            avatar_url=data.get("avatar_url"),
            created_at=data.get("created_at", datetime.utcnow()),
            updated_at=data.get("updated_at"),
        )
        profile.id = doc_id  # Attach the Firestore document ID
        return profile
