"""
Cry Event Model — Defines the structure of cry classification events in Firestore.

Firestore Collection: 'cry_events'
Document ID: Auto-generated by Firestore

When the ESP32 detects a cry, it sends audio features to the backend.
The ML model classifies the cry type and stores the result here.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


# Valid cry types that our model can classify
CRY_TYPES = ["hunger", "pain", "discomfort", "tired", "normal"]


@dataclass
class CryEvent:
    """
    A single cry classification event.

    Firestore path: cry_events/{auto_id}
    """
    baby_id: str                          # Reference to baby_profiles document
    cry_type: str                         # One of CRY_TYPES
    confidence: float = 0.0              # ML model confidence (0.0 to 1.0)
    duration_seconds: Optional[int] = None  # How long the baby cried
    audio_features: Optional[dict] = None   # MFCC features used for classification
    timestamp: datetime = field(default_factory=datetime.utcnow)

    def to_dict(self) -> dict:
        """Convert to dictionary for Firestore storage."""
        return {
            "baby_id": self.baby_id,
            "cry_type": self.cry_type,
            "confidence": self.confidence,
            "duration_seconds": self.duration_seconds,
            "audio_features": self.audio_features,
            "timestamp": self.timestamp,
        }

    @staticmethod
    def from_dict(doc_id: str, data: dict) -> "CryEvent":
        """Create CryEvent instance from Firestore document."""
        event = CryEvent(
            baby_id=data.get("baby_id", ""),
            cry_type=data.get("cry_type", "normal"),
            confidence=data.get("confidence", 0.0),
            duration_seconds=data.get("duration_seconds"),
            audio_features=data.get("audio_features"),
            timestamp=data.get("timestamp", datetime.utcnow()),
        )
        event.id = doc_id
        return event
