"""
Notification Model — Defines the structure of alerts/notifications in Firestore.

Firestore Collection: 'notifications'
Document ID: Auto-generated by Firestore

Notifications are generated when:
- Heart rate exceeds threshold (e.g., > 150 BPM)
- Temperature exceeds threshold (e.g., > 37.5°C)
- Cry is detected and classified
- Sleep pattern is unusual
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


# Notification severity levels
NOTIFICATION_TYPES = ["info", "warning", "critical"]


@dataclass
class Notification:
    """
    An alert or notification for the parent.

    Firestore path: notifications/{auto_id}
    """
    user_id: str                          # Firebase Auth UID of the parent
    baby_id: str                          # Reference to baby_profiles document
    type: str = "info"                    # One of NOTIFICATION_TYPES
    title: str = ""                       # Short title (e.g., "High Heart Rate Alert")
    message: str = ""                     # Detailed message
    is_read: bool = False                 # Has the parent seen this?
    created_at: datetime = field(default_factory=datetime.utcnow)

    def to_dict(self) -> dict:
        """Convert to dictionary for Firestore storage."""
        return {
            "user_id": self.user_id,
            "baby_id": self.baby_id,
            "type": self.type,
            "title": self.title,
            "message": self.message,
            "is_read": self.is_read,
            "created_at": self.created_at,
        }

    @staticmethod
    def from_dict(doc_id: str, data: dict) -> "Notification":
        """Create Notification instance from Firestore document."""
        notif = Notification(
            user_id=data.get("user_id", ""),
            baby_id=data.get("baby_id", ""),
            type=data.get("type", "info"),
            title=data.get("title", ""),
            message=data.get("message", ""),
            is_read=data.get("is_read", False),
            created_at=data.get("created_at", datetime.utcnow()),
        )
        notif.id = doc_id
        return notif
