"""
Sensor Data Model — Defines the structure of sensor readings in Firestore.

Firestore Collection: 'sensor_data'
Document ID: Auto-generated by Firestore

This is the HIGH-VOLUME collection — ESP32 sends data every few seconds
via MQTT → AWS IoT Core → Lambda → Firestore.

Data includes: heart rate, SpO2, temperature, humidity, and motion (IMU).
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


@dataclass
class MotionData:
    """3-axis accelerometer data from MPU6050."""
    x: float = 0.0
    y: float = 0.0
    z: float = 0.0


@dataclass
class SensorData:
    """
    A single sensor reading from the ESP32 wearable.

    Firestore path: sensor_data/{auto_id}
    """
    baby_id: str                          # Reference to baby_profiles document
    device_id: str                        # ESP32 device identifier
    heart_rate: Optional[float] = None    # BPM from MAX30102
    spo2: Optional[float] = None          # Blood oxygen % from MAX30102
    temperature: Optional[float] = None   # °C from BME280/DHT11
    humidity: Optional[float] = None      # % from BME280/DHT11
    motion: MotionData = field(default_factory=MotionData)  # From MPU6050
    timestamp: datetime = field(default_factory=datetime.utcnow)

    def to_dict(self) -> dict:
        """Convert to dictionary for Firestore storage."""
        return {
            "baby_id": self.baby_id,
            "device_id": self.device_id,
            "heart_rate": self.heart_rate,
            "spo2": self.spo2,
            "temperature": self.temperature,
            "humidity": self.humidity,
            "motion": {
                "x": self.motion.x,
                "y": self.motion.y,
                "z": self.motion.z,
            },
            "timestamp": self.timestamp,
        }

    @staticmethod
    def from_dict(doc_id: str, data: dict) -> "SensorData":
        """Create SensorData instance from Firestore document."""
        motion_data = data.get("motion", {})
        reading = SensorData(
            baby_id=data.get("baby_id", ""),
            device_id=data.get("device_id", ""),
            heart_rate=data.get("heart_rate"),
            spo2=data.get("spo2"),
            temperature=data.get("temperature"),
            humidity=data.get("humidity"),
            motion=MotionData(**motion_data) if motion_data else MotionData(),
            timestamp=data.get("timestamp", datetime.utcnow()),
        )
        reading.id = doc_id
        return reading
