"""
Sleep Session Model — Defines the structure of sleep tracking sessions in Firestore.

Firestore Collection: 'sleep_sessions'
Document ID: Auto-generated by Firestore

Sleep stages are estimated from MPU6050 motion data and heart rate variability.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


# Valid sleep stages
SLEEP_STAGES = ["awake", "light", "deep"]


@dataclass
class SleepSession:
    """
    A single sleep tracking session (or stage within a session).

    Firestore path: sleep_sessions/{auto_id}
    """
    baby_id: str                          # Reference to baby_profiles document
    stage: str                            # One of SLEEP_STAGES
    start_time: datetime = field(default_factory=datetime.utcnow)
    end_time: Optional[datetime] = None
    duration_minutes: Optional[int] = None  # Computed from start/end
    quality_score: Optional[int] = None     # 0-100 quality rating

    def to_dict(self) -> dict:
        """Convert to dictionary for Firestore storage."""
        return {
            "baby_id": self.baby_id,
            "stage": self.stage,
            "start_time": self.start_time,
            "end_time": self.end_time,
            "duration_minutes": self.duration_minutes,
            "quality_score": self.quality_score,
        }

    @staticmethod
    def from_dict(doc_id: str, data: dict) -> "SleepSession":
        """Create SleepSession instance from Firestore document."""
        session = SleepSession(
            baby_id=data.get("baby_id", ""),
            stage=data.get("stage", "awake"),
            start_time=data.get("start_time", datetime.utcnow()),
            end_time=data.get("end_time"),
            duration_minutes=data.get("duration_minutes"),
            quality_score=data.get("quality_score"),
        )
        session.id = doc_id
        return session
